image: python 3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  - .cache/pip
  - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/vin/activate
  - pip install -r requirements.txt

test:
  script:
    - pytest
