[mypy]
python_version = 3.11
force-exclude = ["activate_this.py", ".git", ".gitignore", "__pycache__", ".venv", "__init__", ".pytest_cache", "venv"]
disallow_untyped_defs = true
ignore_missing_imports = true
