name: Python package

on: [push]

# env:
#     SECRETV: ${{ secrets.SECRETV }}
#     PUBV: DefaultVar

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
      # You can test your matrix by printing the current Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: TypeTest
        run: mypy .
      - name: PEP8 test
        run: flake8 .
      - name: AppTest
        run: pytest